server:
    port: 8081

spring:
  config:
    activate:
      on-profile: "default"
  application:
    name: customer-service
  datasource:
    url: jdbc:mysql://localhost:3306/customer_db
    username: customer
    password: customer
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl