server:
  port: 8082

spring:
  config:
    activate:
      on-profile: "default"
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://localhost:3306/order_db
    username: order
    password: order
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
